using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.0.1.0")]
[assembly: AssemblyProductAttribute("Etomic.NAntExtensions")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2005, Etomic Ltd.")]

